Repository HSLdevcom/helmet-model-system, pull requests merged in 2020-10, with the labels that each got.

#217 Fixed emme_bindings import in input file validation
  Scripts/helmet_validate_inputfiles.py
Labels: bug

#220 Fix hop parameters
  Scripts/parameters.py
  Scripts/tests/integration/test_models.py
Labels: invalid

#219 Moved parameters to own package and splitted into several modules
  Scripts/assignment/datatypes/car.py
  Scripts/assignment/datatypes/car_specification.py
  Scripts/assignment/datatypes/journey_level.py
  Scripts/assignment/datatypes/transit.py
  Scripts/assignment/departure_time.py
  Scripts/assignment/emme_assignment.py
  Scripts/assignment/mock_assignment.py
  Scripts/datahandling/matrixdata.py
  Scripts/datahandling/zonedata.py
  Scripts/datatypes/demand.py
  Scripts/datatypes/person.py
  Scripts/datatypes/purpose.py
  Scripts/datatypes/tour.py
  Scripts/demand/external.py
  Scripts/demand/freight.py
  Scripts/demand/trips.py
  Scripts/helmet.py
  Scripts/helmet_validate_inputfiles.py
  Scripts/models/generation.py
  Scripts/models/linear.py
  Scripts/models/logit.py
  Scripts/modelsystem.py
  Scripts/parameters.py
  Scripts/parameters/__init__.py
  Scripts/parameters/assignment.py
  Scripts/parameters/car.py
  Scripts/parameters/departure_time.py
  Scripts/parameters/destination_choice.py
  Scripts/parameters/impedance_transformation.py
  Scripts/parameters/mode_choice.py
  Scripts/parameters/tour_generation.py
  Scripts/parameters/zone.py
  Scripts/test_assignment.py
  Scripts/tests/integration/test_data_handling.py
  Scripts/transform/impedance_transformer.py
  Scripts/utils/freight.py
Labels: enhancement

#218 In loop, add transit matrices to transit_work matrix
  Scripts/assignment/emme_assignment.py
Labels: enhancement
